# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Zocker1012
# Avahi-Konfiguration für das Add-on (host_network)
# Nur das Nötige für AirPrint/IPP veröffentlichen: kein Reflector,
# keine Workstation-/HINFO-Einträge, kein Wide-Area-DNS-SD.

[server]
# Wird beim Start auf die LAN-Schnittstellen gesetzt (ohne Docker/hassio/veth)
#allow-interfaces=
use-ipv4=yes
use-ipv6=yes
ratelimit-interval-usec=1000000
ratelimit-burst=1000

[wide-area]
enable-wide-area=no

[publish]
publish-hinfo=no
publish-workstation=no
publish-aaaa-on-ipv4=no

[reflector]
enable-reflector=no

[rlimits]
