name: "CUPS Addon (Brother MFC-260C)"
version: "1.0.2"
slug: cups-brother-mfc260c
description: >
  CUPS print server with Avahi/AirPrint support for the Brother MFC-260C.

url: "https://github.com/Zocker1012/ha-cups-addon"

arch:
  - amd64

startup: services
boot: auto
init: false

# Schutzmechanismen deaktivieren
protection_mode: false
apparmor: false

# Netzwerk
host_network: true

# Ingress (HA UI Zugriff)
ingress: true
ingress_port: 8080

panel_icon: mdi:printer
panel_title: CUPS

# USB Zugriff
usb: true
devices:
  - /dev/bus/usb
  - /dev/usb

# Dateisystem Zugriff
map:
  - config:rw
  - share:rw
  - ssl:rw

# Erweiterte Rechte (für Treiber / Avahi / CUPS Backend)
privileged:
  - SYS_ADMIN
  - SYS_RAWIO
  - NET_ADMIN
  - SYS_NICE
  - DAC_READ_SEARCH
